---
- name: Install snmpd
  ansible.builtin.dnf:
    name: 
      - net-snmp-libs
      - net-snmp-utils
      - net-snmp-agent-libs
      - net-snmp
    state: latest

- name: Set snmpd.conf
  ansible.builtin.copy:
    src: snmpd.conf
    dest: /etc/snmp/snmpd.conf

- name: Enable SNMPD
  ansible.builtin.systemd:
    name: snmpd
    enabled: yes
    state: started

- name: stop firewalld
  ansible.builtin.systemd:
    state: stopped
    name: firewalld
  
- name: Enable udp ports 161 and 162
  ansible.builtin.iptables:
    chain: INPUT
    protocol: udp
    source: 129.11.78.161
    jump: ACCEPT
    action: insert
    rule_num: 2

- name: Check for NVIDIA GPU
  ansible.builtin.shell: nvidia-smi --query-gpu=name --format=csv,noheader,nounits
  ignore_errors: true
  register: gpu_output

- name: Add Nvidia monitoring script
  ansible.builtin.copy:
    src: nvidia_script
    dest: /etc/snmp/nvidia
  when: "'NVIDIA' in gpu_output.stdout"

- name: Make the script executable
  ansible.builtin.file:
    path: /etc/snmp/nvidia
    mode: '0755'
  when: "'NVIDIA' in gpu_output.stdout"

- name: Restart SNMP daemon
  ansible.builtin.service:
    name: snmpd
    state: restarted